<?php
return [
    'NOMBRE DEL AREA',
    'NOMBRE DEL AREA',
    'NOMBRE DEL AREA',
    'NOMBRE DEL AREA',
    'NOMBRE DEL AREA',
    'NOMBRE DEL AREA',
    'NOMBRE DEL AREA',
    'NOMBRE DEL AREA',
    'NOMBRE DEL AREA',
];
